INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Vhagar', 'Unknown');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Seasmoke', 'Gray');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Vermax', 'Unknown');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Arrax', 'White and gold');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Tyraxes', 'Unknown');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Vermithor', 'Bronze');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Silverwing', 'Silver');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Caraxes', 'Blood Red');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Meleys', 'Red');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Sunfyre', 'Golden');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Syrax', 'Yellow');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Tessarion', 'Blue');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Dreamfyre', 'Light blue and silver');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Morning', 'Pink');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Moondancer', 'Pale green');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Stormcloud', 'Unknown');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Sheepstealer', 'Brown');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Cannibal', 'Black');
INSERT INTO dragon (dragon_name, dragon_color) VALUES ('Grey Ghost', 'Grey');
